"""
Meal template database — 20 templates covering Chinese and Western cuisine.

Each template defines:
  name, cuisine, meal_type, cooking_time_minutes,
  preferred_categories (ordered priority list of inventory categories),
  required_categories (at least one must be present),
  macro_profile (rough descriptor),
  tags (used for scoring against diet_style),
  instructions (simple cooking steps).
"""

MEAL_TEMPLATES = [
    # ── Chinese templates ──────────────────────────────────────────────────
    {
        "id": 1,
        "name": "Beef Stir-Fry with Vegetables",
        "cuisine": "chinese",
        "meal_type": "dinner",
        "cooking_time_minutes": 20,
        "preferred_categories": ["meat", "vegetable", "condiment"],
        "required_categories": ["meat", "vegetable"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "low_carb"],
        "instructions": [
            "Slice beef thinly against the grain. Season with soy sauce, cornstarch, and a pinch of pepper.",
            "Heat a wok or large pan over high heat. Add oil and stir-fry beef for 2–3 minutes until browned. Remove and set aside.",
            "In the same pan, stir-fry garlic and vegetables for 3–4 minutes until tender-crisp.",
            "Return beef to the pan. Add soy sauce and a splash of water. Toss everything together for 1 minute.",
            "Serve immediately over steamed rice or on its own.",
        ],
    },
    {
        "id": 2,
        "name": "Tomato Egg Stir-Fry",
        "cuisine": "chinese",
        "meal_type": "lunch",
        "cooking_time_minutes": 15,
        "preferred_categories": ["vegetable", "other", "condiment"],
        "required_categories": ["vegetable", "other"],
        "macro_profile": "balanced",
        "tags": ["balanced", "low_carb", "quick"],
        "instructions": [
            "Beat eggs with a pinch of salt.",
            "Heat oil in a wok. Scramble eggs until just set, then push to the side.",
            "Add chopped tomatoes and stir-fry for 2 minutes until they release their juice.",
            "Mix everything together. Season with sugar, salt, and sesame oil.",
            "Serve hot over steamed rice.",
        ],
    },
    {
        "id": 3,
        "name": "Steamed Rice Bowl with Beef",
        "cuisine": "chinese",
        "meal_type": "lunch",
        "cooking_time_minutes": 10,
        "preferred_categories": ["grain", "meat", "vegetable"],
        "required_categories": ["grain"],
        "macro_profile": "balanced",
        "tags": ["balanced", "high_protein"],
        "instructions": [
            "Warm cooked rice in a bowl.",
            "Slice or shred cooked/leftover meat and arrange on top of rice.",
            "Add any vegetables you have — steamed, raw, or pickled.",
            "Drizzle with soy sauce, a dash of sesame oil, and optionally chilli flakes.",
            "Mix before eating and enjoy.",
        ],
    },
    {
        "id": 4,
        "name": "Congee (Rice Porridge)",
        "cuisine": "chinese",
        "meal_type": "breakfast",
        "cooking_time_minutes": 30,
        "preferred_categories": ["grain", "other", "condiment"],
        "required_categories": ["grain"],
        "macro_profile": "balanced",
        "tags": ["balanced", "low_fat"],
        "instructions": [
            "Combine cooked rice with 4× the volume of water or broth in a pot.",
            "Bring to a boil then reduce to a gentle simmer for 20 minutes, stirring occasionally.",
            "Season with salt and white pepper.",
            "Top with sliced egg (soft-boiled or poached), scallions, and sesame oil.",
            "Optionally add shredded chicken or pork for extra protein.",
        ],
    },
    {
        "id": 5,
        "name": "Garlic Stir-Fried Greens",
        "cuisine": "chinese",
        "meal_type": "lunch",
        "cooking_time_minutes": 10,
        "preferred_categories": ["vegetable", "condiment"],
        "required_categories": ["vegetable"],
        "macro_profile": "low_carb",
        "tags": ["low_carb", "low_fat", "quick"],
        "instructions": [
            "Wash and roughly chop your greens (spinach, bok choy, or any leafy vegetable).",
            "Mince or slice garlic cloves.",
            "Heat oil in a wok or pan over high heat. Sauté garlic for 30 seconds until fragrant.",
            "Add greens and toss vigorously for 2–3 minutes until wilted but still bright green.",
            "Season with salt, a splash of soy sauce, and serve immediately.",
        ],
    },
    {
        "id": 6,
        "name": "Pork and Rice Noodle Bowl",
        "cuisine": "chinese",
        "meal_type": "dinner",
        "cooking_time_minutes": 20,
        "preferred_categories": ["meat", "grain", "vegetable"],
        "required_categories": ["meat"],
        "macro_profile": "balanced",
        "tags": ["balanced", "high_protein"],
        "instructions": [
            "Slice pork thinly and marinate in soy sauce, oyster sauce, and cornstarch for 10 minutes.",
            "Cook rice noodles according to package instructions. Drain and set aside.",
            "Stir-fry pork in a hot wok until cooked through (about 3 minutes).",
            "Add any vegetables and stir-fry for another 2–3 minutes.",
            "Toss with noodles, season to taste, and serve hot.",
        ],
    },
    {
        "id": 7,
        "name": "Steamed Egg Custard",
        "cuisine": "chinese",
        "meal_type": "breakfast",
        "cooking_time_minutes": 20,
        "preferred_categories": ["other", "condiment"],
        "required_categories": ["other"],
        "macro_profile": "balanced",
        "tags": ["balanced", "low_carb", "high_protein"],
        "instructions": [
            "Beat 2–3 eggs with warm water (1:1.5 ratio). Add a pinch of salt.",
            "Strain through a fine sieve to remove bubbles.",
            "Pour into a heatproof bowl and cover with a lid or plastic wrap.",
            "Steam over medium-low heat for 12–15 minutes until just set (should be silky, not rubbery).",
            "Drizzle with soy sauce and sesame oil before serving.",
        ],
    },
    {
        "id": 8,
        "name": "Stir-Fried Shrimp with Broccoli",
        "cuisine": "chinese",
        "meal_type": "dinner",
        "cooking_time_minutes": 15,
        "preferred_categories": ["meat", "vegetable", "condiment"],
        "required_categories": ["meat", "vegetable"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "low_carb", "low_fat", "quick"],
        "instructions": [
            "Season shrimp with salt, pepper, and a little cornstarch.",
            "Blanch broccoli in boiling water for 2 minutes. Drain and set aside.",
            "Heat oil in a wok. Stir-fry garlic for 30 seconds.",
            "Add shrimp and cook until pink (about 2 minutes per side).",
            "Add broccoli, season with soy sauce and oyster sauce, toss together and serve.",
        ],
    },
    # ── Western templates ──────────────────────────────────────────────────
    {
        "id": 9,
        "name": "Grilled Chicken Breast with Salad",
        "cuisine": "western",
        "meal_type": "lunch",
        "cooking_time_minutes": 20,
        "preferred_categories": ["meat", "vegetable", "fruit"],
        "required_categories": ["meat"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "low_carb", "balanced"],
        "instructions": [
            "Season chicken breast with olive oil, salt, pepper, garlic powder, and paprika.",
            "Cook on a preheated grill pan or skillet over medium-high heat for 6–7 minutes per side.",
            "Let rest for 5 minutes before slicing.",
            "While resting, toss your salad greens with a simple dressing (olive oil + lemon juice).",
            "Serve sliced chicken over the salad.",
        ],
    },
    {
        "id": 10,
        "name": "Scrambled Eggs on Toast",
        "cuisine": "western",
        "meal_type": "breakfast",
        "cooking_time_minutes": 10,
        "preferred_categories": ["other", "grain", "dairy"],
        "required_categories": ["other"],
        "macro_profile": "balanced",
        "tags": ["balanced", "high_protein", "quick"],
        "instructions": [
            "Crack eggs into a bowl, add a splash of milk, salt, and pepper. Whisk well.",
            "Melt butter in a non-stick pan over low heat.",
            "Pour in eggs and gently fold with a spatula every few seconds, removing from heat briefly if needed.",
            "Remove while still slightly underdone — they will finish cooking from residual heat.",
            "Serve on toasted bread. Optionally top with cheese or herbs.",
        ],
    },
    {
        "id": 11,
        "name": "Greek Yogurt Parfait",
        "cuisine": "western",
        "meal_type": "breakfast",
        "cooking_time_minutes": 5,
        "preferred_categories": ["dairy", "fruit", "snack", "grain"],
        "required_categories": ["dairy"],
        "macro_profile": "balanced",
        "tags": ["balanced", "high_protein", "low_fat", "quick"],
        "instructions": [
            "Spoon Greek yogurt into a bowl or glass.",
            "Layer with fresh fruit (berries, banana slices, or any fruit you have).",
            "Add a handful of oats, granola, or crushed nuts for crunch.",
            "Drizzle with honey if desired.",
            "Eat immediately or refrigerate for up to 4 hours.",
        ],
    },
    {
        "id": 12,
        "name": "Salmon Salad Bowl",
        "cuisine": "western",
        "meal_type": "lunch",
        "cooking_time_minutes": 15,
        "preferred_categories": ["meat", "vegetable", "fruit"],
        "required_categories": ["meat", "vegetable"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "low_carb", "balanced"],
        "instructions": [
            "Season salmon fillet with salt, pepper, and lemon juice.",
            "Pan-sear or bake at 200°C for 10–12 minutes until cooked through.",
            "Prepare a base of salad greens, cucumber, and any vegetables you have.",
            "Flake salmon over the salad.",
            "Drizzle with olive oil and lemon dressing. Serve immediately.",
        ],
    },
    {
        "id": 13,
        "name": "Beef Burger Bowl",
        "cuisine": "western",
        "meal_type": "dinner",
        "cooking_time_minutes": 25,
        "preferred_categories": ["meat", "vegetable", "dairy"],
        "required_categories": ["meat"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "balanced"],
        "instructions": [
            "Season ground beef with salt, pepper, garlic powder, and Worcestershire sauce. Form into patties.",
            "Cook patties in a skillet over medium-high heat, 4–5 minutes per side.",
            "While cooking, prepare your bowl base: lettuce, tomato, onion, pickles.",
            "Optionally add cheese on top of the patty in the last minute of cooking.",
            "Assemble bowl and drizzle with your favourite sauce.",
        ],
    },
    {
        "id": 14,
        "name": "Pasta with Tomato Sauce",
        "cuisine": "western",
        "meal_type": "dinner",
        "cooking_time_minutes": 20,
        "preferred_categories": ["grain", "vegetable", "condiment"],
        "required_categories": ["grain"],
        "macro_profile": "balanced",
        "tags": ["balanced", "low_fat"],
        "instructions": [
            "Boil pasta in salted water according to package instructions. Reserve ½ cup pasta water before draining.",
            "In a pan, sauté garlic in olive oil for 1 minute. Add diced tomatoes and simmer for 10 minutes.",
            "Season sauce with salt, pepper, and a pinch of sugar. Add fresh basil if available.",
            "Toss pasta with sauce, adding pasta water to adjust consistency.",
            "Serve topped with grated cheese.",
        ],
    },
    {
        "id": 15,
        "name": "Spinach Omelette",
        "cuisine": "western",
        "meal_type": "breakfast",
        "cooking_time_minutes": 15,
        "preferred_categories": ["other", "vegetable", "dairy"],
        "required_categories": ["other"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "low_carb", "quick"],
        "instructions": [
            "Beat 2–3 eggs with salt and pepper.",
            "Wilt spinach in a heated pan with a little oil or butter (about 1 minute). Set aside.",
            "Pour eggs into the pan over medium heat. Do not stir — let the edges set.",
            "Add spinach and optionally cheese over one half of the omelette.",
            "Fold the omelette in half and slide onto a plate. Serve immediately.",
        ],
    },
    {
        "id": 16,
        "name": "Tuna Avocado Salad",
        "cuisine": "western",
        "meal_type": "lunch",
        "cooking_time_minutes": 10,
        "preferred_categories": ["meat", "vegetable", "fruit"],
        "required_categories": ["meat"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "low_carb", "quick"],
        "instructions": [
            "Drain canned tuna and flake into a bowl.",
            "Dice avocado and any other vegetables (cucumber, cherry tomatoes, onion).",
            "Mix tuna with vegetables. Add a squeeze of lemon juice, salt, and pepper.",
            "Optionally add a dollop of Greek yogurt or mayo for creaminess.",
            "Serve on lettuce leaves or over a bed of greens.",
        ],
    },
    {
        "id": 17,
        "name": "Avocado Toast",
        "cuisine": "western",
        "meal_type": "breakfast",
        "cooking_time_minutes": 10,
        "preferred_categories": ["grain", "fruit", "other"],
        "required_categories": ["grain", "fruit"],
        "macro_profile": "balanced",
        "tags": ["balanced", "low_fat", "quick"],
        "instructions": [
            "Toast slices of bread until golden.",
            "Mash a ripe avocado with salt, pepper, and lemon juice.",
            "Spread avocado generously over the toast.",
            "Top with optional extras: sliced egg, chilli flakes, seeds, or tomato.",
            "Eat immediately.",
        ],
    },
    {
        "id": 18,
        "name": "Protein Smoothie Bowl",
        "cuisine": "western",
        "meal_type": "snack",
        "cooking_time_minutes": 5,
        "preferred_categories": ["dairy", "fruit", "grain", "snack"],
        "required_categories": ["dairy", "fruit"],
        "macro_profile": "balanced",
        "tags": ["balanced", "high_protein", "quick"],
        "instructions": [
            "Blend Greek yogurt with frozen or fresh fruit until smooth and thick.",
            "Pour into a bowl — the consistency should be thicker than a drinkable smoothie.",
            "Top with sliced fresh fruit, oats, granola, nuts, or seeds.",
            "Add a drizzle of honey if desired.",
            "Eat with a spoon.",
        ],
    },
    {
        "id": 19,
        "name": "Chicken and Rice Bowl",
        "cuisine": "western",
        "meal_type": "lunch",
        "cooking_time_minutes": 15,
        "preferred_categories": ["meat", "grain", "vegetable"],
        "required_categories": ["meat", "grain"],
        "macro_profile": "high_protein",
        "tags": ["high_protein", "balanced"],
        "instructions": [
            "Dice chicken breast and season with salt, pepper, garlic powder, and paprika.",
            "Pan-cook chicken in oil over medium-high heat for 5–7 minutes until golden and cooked through.",
            "Warm cooked rice and portion into a bowl.",
            "Add steamed or roasted vegetables alongside the chicken.",
            "Drizzle with sauce of choice (hot sauce, tzatziki, or soy-based glaze) and serve.",
        ],
    },
    {
        "id": 20,
        "name": "Oatmeal Breakfast Bowl",
        "cuisine": "western",
        "meal_type": "breakfast",
        "cooking_time_minutes": 10,
        "preferred_categories": ["grain", "fruit", "dairy"],
        "required_categories": ["grain"],
        "macro_profile": "balanced",
        "tags": ["balanced", "low_fat"],
        "instructions": [
            "Combine oats with milk or water in a saucepan (1:2 ratio). Bring to a simmer.",
            "Cook over medium heat for 5 minutes, stirring occasionally, until creamy.",
            "Remove from heat and let sit for 1 minute.",
            "Top with sliced banana, berries, or any fresh fruit.",
            "Add a spoonful of nut butter or a drizzle of honey for extra flavour.",
        ],
    },
]


def get_templates_for_meal_type(meal_type: str) -> list:
    return [t for t in MEAL_TEMPLATES if t["meal_type"] == meal_type]


def get_all_templates() -> list:
    return MEAL_TEMPLATES
