CREATE TABLE IF NOT EXISTS inventory_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    quantity          DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit              VARCHAR(50)  NOT NULL DEFAULT 'g',
    zone              VARCHAR(50)  NOT NULL DEFAULT 'fridge',
    category          VARCHAR(100),
    best_before_date  DATE,
    calories_per_100g DOUBLE PRECISION,
    protein_per_100g  DOUBLE PRECISION,
    carbs_per_100g    DOUBLE PRECISION,
    fat_per_100g      DOUBLE PRECISION,
    version           BIGINT NOT NULL DEFAULT 0,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inventory_zone ON inventory_items(zone);
CREATE INDEX IF NOT EXISTS idx_inventory_best_before ON inventory_items(best_before_date);
