CREATE TABLE IF NOT EXISTS daily_nutrition_logs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              VARCHAR(100) NOT NULL DEFAULT 'default',
    log_date             DATE         NOT NULL,
    calories_consumed    DOUBLE PRECISION NOT NULL DEFAULT 0,
    protein_g_consumed   DOUBLE PRECISION NOT NULL DEFAULT 0,
    carbs_g_consumed     DOUBLE PRECISION NOT NULL DEFAULT 0,
    fat_g_consumed       DOUBLE PRECISION NOT NULL DEFAULT 0,
    version              BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_date UNIQUE (user_id, log_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_log_user_date ON daily_nutrition_logs(user_id, log_date);
