CREATE TABLE IF NOT EXISTS meal_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_log_id  BIGINT       NOT NULL REFERENCES daily_nutrition_logs(id),
    user_id       VARCHAR(100) NOT NULL DEFAULT 'default',
    meal_type     VARCHAR(50)  NOT NULL,
    meal_name     VARCHAR(255) NOT NULL,
    calories      DOUBLE PRECISION NOT NULL DEFAULT 0,
    protein_g     DOUBLE PRECISION NOT NULL DEFAULT 0,
    carbs_g       DOUBLE PRECISION NOT NULL DEFAULT 0,
    fat_g         DOUBLE PRECISION NOT NULL DEFAULT 0,
    source        VARCHAR(50)  NOT NULL DEFAULT 'manual',
    notes         TEXT,
    logged_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_meal_log_daily   ON meal_logs(daily_log_id);
CREATE INDEX IF NOT EXISTS idx_meal_log_user_at ON meal_logs(user_id, logged_at);
